conda-forge/biorbd-feedstock

recipe/meta.yaml

Added Ipopt as dependency

---

recipe/meta.yaml

Version 1.1.3

---

recipe/meta.yaml

Bumped to 1.2.0

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
recipe/meta.yaml

pin_compatible

---

recipe/meta.yaml

Bumped to 1.2.5

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_backendcasadibackend_name_in_buildCasadipython3.6.____cpython.yaml
.ci_support/linux_backendcasadibackend_name_in_buildCasadipython3.7.____cpython.yaml
.ci_support/linux_backendcasadibackend_name_in_buildCasadipython3.8.____cpython.yaml
.ci_support/linux_backendeigenbackend_name_in_buildEigen3python3.6.____cpython.yaml
.ci_support/linux_backendeigenbackend_name_in_buildEigen3python3.7.____cpython.yaml
.ci_support/linux_backendeigenbackend_name_in_buildEigen3python3.8.____cpython.yaml
.ci_support/osx_backendcasadibackend_name_in_buildCasadipython3.6.____cpython.yaml
.ci_support/osx_backendcasadibackend_name_in_buildCasadipython3.7.____cpython.yaml
.ci_support/osx_backendcasadibackend_name_in_buildCasadipython3.8.____cpython.yaml
.ci_support/osx_backendeigenbackend_name_in_buildEigen3python3.6.____cpython.yaml
.ci_support/osx_backendeigenbackend_name_in_buildEigen3python3.7.____cpython.yaml
.ci_support/osx_backendeigenbackend_name_in_buildEigen3python3.8.____cpython.yaml
.ci_support/win_python3.6.____cpython.yaml
.ci_support/win_python3.7.____cpython.yaml
README.md
recipe/bld.bat
recipe/build.sh
recipe/conda_build_config.yaml
recipe/meta.yaml

Build alonside with casadi

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml

Allowed for casadi and py38

---

recipe/meta.yaml

Version 1.3.5

---

recipe/meta.yaml

Bumped to 1.4.0

---

.azure-pipelines/azure-pipelines-win.yml
.ci_support/win_64_backendcasadibackend_name_in_buildCasadipython3.6.____cpython.yaml
.ci_support/win_64_backendcasadibackend_name_in_buildCasadipython3.7.____cpython.yaml
.ci_support/win_64_backendcasadibackend_name_in_buildCasadipython3.8.____cpython.yaml
.ci_support/win_64_backendcasadibackend_name_in_buildCasadipython3.9.____cpython.yaml
.ci_support/win_64_backendeigenbackend_name_in_buildEigen3python3.6.____cpython.yaml
.ci_support/win_64_backendeigenbackend_name_in_buildEigen3python3.7.____cpython.yaml
.ci_support/win_64_backendeigenbackend_name_in_buildEigen3python3.8.____cpython.yaml
.ci_support/win_64_backendeigenbackend_name_in_buildEigen3python3.9.____cpython.yaml
README.md
recipe/conda_build_config.yaml
recipe/meta.yaml

Added windows for CasADi backend

---

.azure-pipelines/azure-pipelines-linux.yml
recipe/meta.yaml

Bumped to 1.5.4

---

.ci_support/linux_64_.yaml
.ci_support/osx_64_.yaml
.ci_support/win_64_.yaml
recipe/meta.yaml

Bumped to 1.8.0

---

recipe/meta.yaml

Bumped to 1.9.3

---

recipe/meta.yaml

Bumped to 1.9.5

---

recipe/meta.yaml

Updated to new release

---

recipe/meta.yaml

Bumped to num 1

---

.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_numpy1.21python3.10.____cpython.yaml
.ci_support/linux_64_numpy1.23python3.11.____cpython.yaml
.ci_support/migrations/ipopt31411.yaml
.ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
.ci_support/osx_64_numpy1.23python3.11.____cpython.yaml
.ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
.ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
README.md
recipe/meta.yaml

Forced compilation so casadi 3.6.2 is included

---

.ci_support/osx_64_numpy1.22python3.10.____cpython.yaml
.ci_support/osx_64_numpy1.23python3.11.____cpython.yaml
.ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml
.ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
recipe/meta.yaml

bumped to 1.10.1

---

.ci_support/linux_64_numpy1.26python3.12.____cpython.yaml
.ci_support/osx_64_numpy1.26python3.12.____cpython.yaml
.ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml
.ci_support/win_64_numpy1.26python3.12.____cpython.yaml
README.md
recipe/meta.yaml

Bumped to 1.10.2

---

recipe/meta.yaml

New version of 1.10.2

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_numpy1.22python3.10.____cpython.yaml
.ci_support/linux_64_numpy1.23python3.11.____cpython.yaml
.ci_support/linux_64_numpy1.26python3.12.____cpython.yaml
.ci_support/osx_64_numpy1.22python3.10.____cpython.yaml
.ci_support/osx_64_numpy1.23python3.11.____cpython.yaml
.ci_support/osx_64_numpy1.26python3.12.____cpython.yaml
.ci_support/osx_arm64_numpy1.22python3.10.____cpython.yaml
.ci_support/osx_arm64_numpy1.23python3.11.____cpython.yaml
.ci_support/osx_arm64_numpy1.26python3.12.____cpython.yaml
.ci_support/win_64_numpy1.22python3.10.____cpython.yaml
.ci_support/win_64_numpy1.23python3.11.____cpython.yaml
.ci_support/win_64_numpy1.26python3.12.____cpython.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
azure-pipelines.yml
recipe/meta.yaml

Bumped to 1.11.0

---

recipe/meta.yaml

Forced rebuilt

---

recipe/meta.yaml

Force rebuild
